import { useEffect, useMemo, useState } from "react";

import useFilterStore from "../stores/filters.store";

export const usePlantHook = () => {
  const [randomPlants, setRandomPlants] = useState([]);

  useEffect(() => {
    const res = getRandomObjects(allPlants);
    setRandomPlants(res);
  }, []);
  const allPlants = [
    {
      name: "Italian Cypress",
      nameSpanish: "Ciprés italiano",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1754962687/italianCedar_msitci.png",
      desc: "",
      tipo: ["Árboles grandes", "Exterior"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Grande"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado", "Resistente al calor"],
      mascotas: true,
    },
    {
      name: "Lemon Cedar Spiral",
      nameSpanish: "Cedro limón en espiral",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1754963032/lemoncedar_xwbq9y.png",
      desc: "",
      tipo: ["Árboles grandes", "Exterior"],
      luzRequerida: ["Sol directo", "Sombra parcial"],
      tamanio: ["Mediana", "Grande"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: true,
    },
    {
      name: "Sweetgum",
      nameSpanish: "Liquidambar",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1754963262/Sweetgumv2_vew7ta.png",
      desc: "",
      tipo: ["Árboles grandes", "Exterior"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Grande"],
      riego: ["Moderado"],
      clima: ["Clima templado", "Resistente al frío"],
      mascotas: true,
    },
    {
      name: "Maxi Martinel",
      nameSpanish: "Maxi Martinel",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1754963612/maximartinelv3_ioujox.png",
      desc: "",
      tipo: ["Árboles medianos", "Exterior"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: true,
    },
    {
      name: "Dollar Tree",
      nameSpanish: "Dólar",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1754963811/dollartreev3_chuaqh.png",
      desc: "",
      tipo: ["Árboles medianos", "Exterior"],
      luzRequerida: ["Sol directo", "Sombra parcial"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: true,
    },
    {
      name: "Eucalyptus",
      nameSpanish: "Eucalipto",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1754964111/Eucalyptusv3_rpajll.png",
      desc: "",
      tipo: ["Árboles grandes", "Exterior"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Grande"],
      riego: ["Moderado"],
      clima: ["Clima templado", "Resistente al calor"],
      mascotas: false,
    },
    {
      name: "Fir Tree",
      nameSpanish: "Oyamel",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1754964554/oyamelv4_weikga.png",
      desc: "",
      tipo: ["Árboles grandes", "Exterior"],
      luzRequerida: ["Sombra parcial"],
      tamanio: ["Grande"],
      riego: ["Moderado"],
      clima: ["Resistente al frío"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Purple Acadia",
      nameSpanish: "Acacia morada",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1754965981/acaciomoradav4_vwyupy.png",
      desc: "",
      tipo: ["Árboles medianos", "Exterior"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Araucarias",
      nameSpanish: "Araucarias",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1754966924/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_0_1_uu3xea.png",
      desc: "",
      tipo: ["Árboles grandes", "Exterior"],
      luzRequerida: ["Sol directo", "Sombra parcial"],
      tamanio: ["Grande"],
      riego: ["Moderado"],
      clima: ["Clima templado", "Resistente al frío"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "White Cedar",
      nameSpanish: "Cedro blanco",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1754968689/cedroblancov4_qhnhwm.png",
      desc: "",
      tipo: ["Árboles grandes", "Exterior"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Grande"],
      riego: ["Moderado"],
      clima: ["Clima templado", "Resistente al frío"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Old Gold",
      nameSpanish: "Oro viejo",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755056693/oroviejov5_pn1jhw.png",
      desc: "",
      tipo: ["Árboles medianos", "Exterior"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Ocote Pine",
      nameSpanish: "Ocote",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755057064/ocotev4_ydgmbu.png",
      desc: "",
      tipo: ["Árboles grandes", "Exterior"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Grande"],
      riego: ["Moderado"],
      clima: ["Clima templado", "Resistente al frío"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Crawling Yumipero",
      nameSpanish: "Yumipero rastrero",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755057498/yuniperorastrerov5_ju8b5d.png",
      desc: "",
      tipo: ["Exterior"],
      luzRequerida: ["Sol directo", "Sombra parcial"],
      tamanio: ["Pequeña", "Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Bonsai Trees",
      nameSpanish: "Árboles bonsai",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755061792/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_0_3_qmaquv.png",
      desc: "",
      tipo: ["Interior", "Exterior"],
      luzRequerida: ["Sol directo", "Sombra parcial", "Interior con poca luz"],
      tamanio: ["Pequeña", "Mediana"],
      riego: ["Moderado", "Requiere riego frecuente"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Tuliá",
      nameSpanish: "Tuliá",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755062500/tuliav4_rvyoqa.png",
      desc: "",
      tipo: ["Exterior"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Cedrela",
      nameSpanish: "Cedrela",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755062829/cedrelav4_jb84ws.png",
      desc: "",
      tipo: ["Árboles pequeños", "Exterior"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Grande"],
      riego: ["Moderado"],
      clima: ["Clima templado", "Resistente al calor"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Lemon Cedar",
      nameSpanish: "Cedro limón",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755064195/lemontreev4_zgas0h.png",
      desc: "",
      tipo: ["Árboles pequeños", "Exterior"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Mediana", "Grande"],
      riego: ["Moderado"],
      clima: ["Clima templado", "Resistente al calor"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Jacaranda",
      nameSpanish: "Jacarandá",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755064330/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_0_4_oddujt.png",
      desc: "",
      tipo: ["Árboles pequeños", "Exterior"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Grande"],
      riego: ["Moderado"],
      clima: ["Clima templado", "Resistente al calor"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Ficus",
      nameSpanish: "Ficus",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755064535/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_1_locl3i.png",
      desc: "",
      tipo: ["Interior", "Exterior"],
      luzRequerida: ["Sombra parcial", "Interior con poca luz"],
      tamanio: ["Mediana", "Grande"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Coco plumoso",
      nameSpanish: "Coco plumoso",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755064674/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_1_1_effkt6.png",
      desc: "",
      tipo: ["Exterior"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado", "Resistente al calor"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Coco plumoso grande",
      nameSpanish: "Coco plumoso grande",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755065165/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_0_5_on4ilr.png",
      desc: "",
      tipo: ["Exterior"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Grande"],
      riego: ["Moderado"],
      clima: ["Clima templado", "Resistente al calor"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Abanico",
      nameSpanish: "Abanico",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755144506/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_0_10_rpg48l.png",
      desc: "",
      tipo: ["Exterior"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Mediana", "Grande"],
      riego: ["Moderado"],
      clima: ["Clima templado", "Resistente al calor"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Rubelina",
      nameSpanish: "Rubelina",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755143973/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_1_2_vssbn3.png",
      desc: "",
      tipo: ["Exterior"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Grande"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Zica",
      nameSpanish: "Zica",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755144185/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_0_9_e5hybc.png",
      desc: "",
      tipo: ["Exterior"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Licua",
      nameSpanish: "Licua",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755143771/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_0_7_joxvdt.png",
      desc: "",
      tipo: ["Exterior"],
      luzRequerida: ["Sol directo", "Sombra parcial"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Maranta sapito",
      nameSpanish: "Maranta sapito",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755144772/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_0_11_lr0ebg.png",
      desc: "",
      tipo: ["Interior"],
      luzRequerida: [
        "Interior con poca luz",
        "Interior con luz brillante indirecta",
      ],
      tamanio: ["Pequeña"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Peperomia clusifolia",
      nameSpanish: "Peperomia clusifolia",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755145750/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_1_4_vtfmue.png",
      desc: "",
      tipo: ["Interior"],
      luzRequerida: [
        "Interior con poca luz",
        "Interior con luz brillante indirecta",
      ],
      tamanio: ["Pequeña"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Peperomia magnolifolia",
      nameSpanish: "Peperomia magnolifolia",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755146664/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_0_12_pqp3ez.png",
      desc: "",
      tipo: ["Interior"],
      luzRequerida: [
        "Interior con poca luz",
        "Interior con luz brillante indirecta",
      ],
      tamanio: ["Pequeña", "Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Pitosporo",
      nameSpanish: "Pitosporo",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1754772697/Pitosporo_edtzqu.png",
      desc: "",
      tipo: ["Exterior", "Interior"],
      luzRequerida: ["Sol directo", "Sombra parcial"],
      tamanio: ["Mediana", "Grande"],
      riego: ["Moderado"],
      clima: ["Resistente al frío", "Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Caladium",
      nameSpanish: "Caladium",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755146950/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_1_5_bckvsd.png",
      desc: "",
      tipo: ["Interior"],
      luzRequerida: ["Sombra parcial", "Interior con luz brillante indirecta"],
      tamanio: ["Pequeña", "Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Tóxica para mascotas"],
    },
    {
      name: "Maranta",
      nameSpanish: "Maranta",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755147878/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_1_6_feqgey.png",
      desc: "",
      tipo: ["Interior"],
      luzRequerida: [
        "Interior con poca luz",
        "Interior con luz brillante indirecta",
      ],
      tamanio: ["Pequeña"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Millonaria",
      nameSpanish: "Millonaria",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755148041/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_0_13_sm0bqg.png",
      desc: "",
      tipo: ["Exterior", "Interior"],
      luzRequerida: ["Sol directo", "Sombra parcial"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Copal/incienso",
      nameSpanish: "Copal/incienso",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755148486/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_0_15_nagkuo.png",
      desc: "",
      tipo: ["Exterior"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Grande"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado", "Resistente al calor"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Colisadra verde",
      nameSpanish: "Colisadra verde",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755148866/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_1_7_gzboji.png",
      desc: "",
      tipo: ["Interior", "Exterior"],
      luzRequerida: ["Sombra parcial", "Interior con luz brillante indirecta"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Hoja plateada",
      nameSpanish: "Hoja plateada",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755149520/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_1_9_wnpp8g.png",
      desc: "",
      tipo: ["Interior"],
      luzRequerida: ["Sombra parcial", "Interior con poca luz"],
      tamanio: ["Pequeña", "Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Hiedra azul",
      nameSpanish: "Hiedra azul",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755149728/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_1_10_jnmefu.png",
      desc: "",
      tipo: ["Interior", "Exterior"],
      luzRequerida: ["Sombra parcial", "Sol directo"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado", "Resistente al frío"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Colisadra",
      nameSpanish: "Colisadra",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755149143/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_1_8_p0wc5c.png",
      desc: "",
      tipo: ["Interior"],
      luzRequerida: [
        "Interior con poca luz",
        "Interior con luz brillante indirecta",
      ],
      tamanio: ["Pequeña", "Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Zapatilla",
      nameSpanish: "Zapatilla",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755149917/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_0_16_ndm8un.png",
      desc: "",
      tipo: ["Interior"],
      luzRequerida: [
        "Interior con poca luz",
        "Interior con luz brillante indirecta",
      ],
      tamanio: ["Pequeña", "Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Tóxica para mascotas"],
    },
    {
      name: "Payasito",
      nameSpanish: "Payasito",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755150546/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_1_11_jaqqni.png",
      desc: "",
      tipo: ["Interior"],
      luzRequerida: ["Interior con poca luz"],
      tamanio: ["Pequeña"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Spider Plant",
      nameSpanish: "Cortina",
      scientificName: "Chlorophytum comosum",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755150715/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_0_17_llgxgx.png",
      desc: "",
      tipo: ["Interior", "Arbustos"],
      luzRequerida: ["Interior con luz brillante indirecta"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Peace Lily",
      nameSpanish: "Cuna de Moisés",
      scientificName: "Spathiphyllum spp.",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1754775714/cunamoOri_cx84jf.png",
      desc: "",
      tipo: ["Interior", "Flores"],
      luzRequerida: [
        "Interior con poca luz",
        "Interior con luz brillante indirecta",
      ],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Tóxica para mascotas"],
    },
    {
      name: "Roses",
      nameSpanish: "Rosales",
      scientificName: "Rosa spp.",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1754775866/AlbedoBase_XL_A_minimalistic_2D_flat_illustration_of_a_plant_c_0_4_ileneb.png",
      desc: "",
      tipo: ["Exterior", "Flores", "Arbustos"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Mediana", "Grande"],
      riego: ["Moderado"],
      clima: ["Clima templado", "Resistente al frío"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Tuberose",
      nameSpanish: "Tuberosa",
      scientificName: "Polianthes tuberosa",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755150907/Leonardo_Vision_XL_A_minimalistic_flat_image_of_a_plant_called_1_12_ffou2z.png",
      desc: "",
      tipo: ["Exterior", "Flores"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Rocio pinto",
      nameSpanish: "Rocío pinto",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755576949/Rocio_pinto_lzjw72.png",
      desc: "",
      tipo: ["Exterior", "Suculentas"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Rococo",
      nameSpanish: "Rococó",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755576983/rococo_umpt1k.png",
      desc: "",
      tipo: ["Exterior", "Suculentas"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Dedo moro azul",
      nameSpanish: "Dedo moro azul",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755577144/Dedo_moro_azu_aig8qv.png",
      desc: "",
      tipo: ["Exterior", "Suculentas"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Pequeña"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Defin",
      nameSpanish: "Defin",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755577173/Defin_imrtu6.png",
      desc: "",
      tipo: ["Interior", "Suculentas"],
      luzRequerida: ["Sombra parcial", "Interior con poca luz"],
      tamanio: ["Pequeña"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Uña de señorita",
      nameSpanish: "Uña de señorita",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755577284/se%C3%B3rita_z4qavg.png",
      desc: "",
      tipo: ["Interior", "Suculentas"],
      luzRequerida: ["Sombra parcial", "Interior con luz brillante indirecta"],
      tamanio: ["Pequeña"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },

    {
      name: "Sineraria",
      nameSpanish: "Sineraria",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755577344/Sineraria_2_ejhhky.png",
      desc: "",
      tipo: ["Interior", "Suculentas"],
      luzRequerida: ["Sombra parcial"],
      tamanio: ["Pequeña", "Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Cola de zorro",
      nameSpanish: "Cola de zorro",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755577393/coladzorro_nzgdfv.png",
      desc: "",
      tipo: ["Exterior", "Suculentas"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Bisnaga espina amarilla",
      nameSpanish: "Bisnaga espina amarilla",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755577466/bisnaga_espina_amarilla_qy35yc.png",
      desc: "",
      tipo: ["Exterior", "Suculentas", "Cactus"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Pequeña"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado"],
      mascotas: ["Tóxica para mascotas"],
    },
    {
      name: "Viejito",
      nameSpanish: "Viejito",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755577501/viejito_kaoqbr.png",
      desc: "",
      tipo: ["Exterior", "Suculentas", "Cactus"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Pequeña"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Cola de chango",
      nameSpanish: "Cola de chango",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755577594/Cola_de_chango_yzf9z2.png",
      desc: "",
      tipo: ["Exterior", "Suculentas"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Cactus estrella",
      nameSpanish: "Cactus estrella",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755577649/cactus_estrella_2_y944bw.png",
      desc: "",
      tipo: ["Exterior", "Suculentas", "Cactus"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Pequeña", "Mediana"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Bejunco",
      nameSpanish: "Bejunco",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755577687/Bejunco_gi7mlt.png",
      desc: "",
      tipo: ["Exterior", "Suculentas"],
      luzRequerida: ["Sol directo", "Sombra parcial"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Corona de cristo",
      nameSpanish: "Corona de cristo",
      scientificName: "Euphorbia milii",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755577726/corona_de_cristo_fkogcu.png",
      desc: "",
      tipo: ["Exterior", "Arbustos"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado", "Resistente al calor"],
      mascotas: ["Tóxica para mascotas"],
    },
    {
      name: "Cebra",
      nameSpanish: "Cebra",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755577761/Cebra_tdrtpu.png",
      desc: "",
      tipo: ["Interior", "Suculentas"],
      luzRequerida: ["Sombra parcial", "Interior con luz brillante indirecta"],
      tamanio: ["Pequeña"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Anillo de flores",
      nameSpanish: "Anillo de flores",
      scientificName: "",
      imageUrl: "",
      desc: "",
      tipo: ["Interior", "Exterior", "Flores"],
      luzRequerida: ["Sol directo", "Sombra parcial"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Mammilaria karwinskiana",
      nameSpanish: "Mammilaria karwinskiana",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755577948/mammillaris_c1cdfo.png",
      desc: "",
      tipo: ["Exterior", "Suculentas", "Cactus"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Pequeña"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado", "Resistente al calor"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Lila de pascua",
      nameSpanish: "Lila de pascua",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755578026/lila_de_pascua_dco2vb.png",
      desc: "",
      tipo: ["Exterior", "Flores"],
      luzRequerida: ["Sol directo", "Sombra parcial"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado", "Resistente al frío"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Cactus Mickey",
      nameSpanish: "Cactus Mickey",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755578061/Cactus_Mickey_rdoy5o.png",
      desc: "",
      tipo: ["Exterior", "Cactus"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Pequeña"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Resistente al calor"],
      mascotas: ["Pet friendly"],
    },

    {
      name: "Mammilaria hanhiana",
      nameSpanish: "Mammilaria hanhiana",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755577928/Mammilaria_hanhiana_capt47.png",
      desc: "",
      tipo: ["Exterior", "Cactus"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Pequeña"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },

    {
      name: "Estrella marina",
      nameSpanish: "Estrella marina",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755578240/estrella_marina_ibc8f0.png",
      desc: "",
      tipo: ["Interior", "Suculentas"],
      luzRequerida: ["Sombra parcial", "Interior con luz brillante indirecta"],
      tamanio: ["Pequeña"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Erizo de mar",
      nameSpanish: "Erizo de mar",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755578271/erizo_g8uilb.png",
      desc: "",
      tipo: ["Exterior", "Cactus"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Pequeña"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Resistente al calor"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Mammilaria compresa",
      nameSpanish: "Mammilaria compresa",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755578303/Mammilaria_compresa_sjve4d.png",
      desc: "",
      tipo: ["Exterior", "Cactus"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Pequeña"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Resistente al calor", "Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Cactus navideño",
      nameSpanish: "Cactus navideño",
      scientificName: "Schlumbergera truncata",
      imageUrl: "",
      desc: "",
      tipo: ["Interior", "Suculentas"],
      luzRequerida: ["Interior con luz brillante indirecta", "Sombra parcial"],
      tamanio: ["Pequeña"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Dama de noche",
      nameSpanish: "Dama de noche",
      scientificName: "Cestrum nocturnum",
      imageUrl: "",
      desc: "",
      tipo: ["Exterior", "Arbustos"],
      luzRequerida: ["Sol directo", "Sombra parcial"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Tóxica para mascotas"],
    },
    {
      name: "Corona de cristo doble",
      nameSpanish: "Corona de cristo doble",
      scientificName: "Euphorbia milii",
      imageUrl: "",
      desc: "",
      tipo: ["Exterior", "Arbustos"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Resistente al calor"],
      mascotas: ["Tóxica para mascotas"],
    },
    {
      name: "Cactus mini",
      nameSpanish: "Cactus mini",
      scientificName: "",
      imageUrl: "",
      desc: "",
      tipo: ["Exterior", "Cactus"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Pequeña"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Resistente al calor"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Pachipodium",
      nameSpanish: "Pachipodium",
      scientificName: "Pachypodium lamerei",
      imageUrl: "",
      desc: "",
      tipo: ["Exterior", "Suculentas"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Mediana"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Resistente al calor"],
      mascotas: ["Tóxica para mascotas"],
    },
    {
      name: "Gladiolus",
      nameSpanish: "Elia",
      scientificName: "Gladiolus spp.",
      imageUrl: "",
      desc: "",
      tipo: ["Exterior", "Flores"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Tóxica para mascotas"],
    },
    {
      name: "Marginata rosa",
      nameSpanish: "Marginata rosa",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755659652/Marginata_rosa_vfmibs.png",
      desc: "",
      tipo: ["Interior"],
      luzRequerida: ["Interior con poca luz", "Sombra parcial"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado", "Resistente al calor"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Marginata",
      nameSpanish: "Marginata",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755659697/marginata_mm9eoq.png",
      desc: "",
      tipo: ["Interior"],
      luzRequerida: ["Interior con poca luz", "Sombra parcial"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado", "Resistente al calor"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Aralia china",
      nameSpanish: "Aralia china",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755659785/ariala_china_ffnki2.png",
      desc: "",
      tipo: ["Interior", "Exterior"],
      luzRequerida: ["Sombra parcial", "Interior con poca luz"],
      tamanio: ["Mediana", "Grande"],
      riego: ["Moderado"],
      clima: ["Clima templado", "Resistente al frío"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Aralia chiflera",
      nameSpanish: "Aralia chiflera",
      scientificName: "",
      imageUrl: "",
      desc: "",
      tipo: ["Interior", "Exterior"],
      luzRequerida: ["Sombra parcial", "Interior con poca luz"],
      tamanio: ["Mediana", "Grande"],
      riego: ["Moderado"],
      clima: ["Clima templado", "Resistente al frío"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Amoena",
      nameSpanish: "Amoena",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755659979/amoena_qv33rv.png",
      desc: "",
      tipo: ["Interior"],
      luzRequerida: ["Interior con poca luz", "Sombra parcial"],
      tamanio: ["Pequeña", "Mediana"],
      riego: ["Moderado", "Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Garra de león",
      nameSpanish: "Garra de león",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755660033/garra_leon_aqssmq.png",
      desc: "",
      tipo: ["Interior"],
      luzRequerida: ["Interior con poca luz", "Sombra parcial"],
      tamanio: ["Pequeña", "Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Areca",
      nameSpanish: "Areca",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755660072/areca_h2x0a9.png",
      desc: "",
      tipo: ["Interior", "Exterior"],
      luzRequerida: ["Sombra parcial", "Interior con poca luz"],
      tamanio: ["Mediana", "Grande"],
      riego: ["Moderado", "Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado", "Resistente al calor"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Muñeca",
      nameSpanish: "Muñeca",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755660109/Mu%C3%B1eca_aqqoov.png",
      desc: "",
      tipo: ["Interior"],
      luzRequerida: ["Sombra parcial", "Interior con poca luz"],
      tamanio: ["Pequeña", "Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Telefono",
      nameSpanish: "Teléfono",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755660143/telefono_2_negadp.png",
      desc: "",
      tipo: ["Interior", "Exterior"],
      luzRequerida: ["Sol directo", "Sombra parcial"],
      tamanio: ["Mediana", "Grande"],
      riego: ["Moderado"],
      clima: ["Clima templado", "Resistente al calor"],
      mascotas: ["Pet friendly"],
    },

    {
      name: "Aralia pinta",
      nameSpanish: "Aralia pinta",
      scientificName: "",
      imageUrl: "",
      desc: "",
      tipo: ["Interior"],
      luzRequerida: ["Interior con poca luz", "Sombra parcial"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },

    {
      name: "Colio",
      nameSpanish: "Colio",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755660200/colio_sk5dtj.png",
      desc: "",
      tipo: ["Exterior"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Mediana", "Grande"],
      riego: ["Requiere riego frecuente"],
      clima: ["Resistente al calor"],
      mascotas: ["Tóxica para mascotas"],
    },
    {
      name: "Sensitiva",
      nameSpanish: "Sensitiva",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755660235/sensitiva_vovpor.png",
      desc: "",
      tipo: ["Interior", "Exterior"],
      luzRequerida: ["Sombra parcial", "Interior con poca luz"],
      tamanio: ["Pequeña"],
      riego: ["Moderado", "Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Orega de elefante",
      nameSpanish: "Oreja de elefante",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755660274/oreja_fante_ywsiu6.png",
      desc: "",
      tipo: ["Interior", "Exterior"],
      luzRequerida: [
        "Sol directo",
        "Sombra parcial",
        "Interior con luz brillante indirecta",
      ],
      tamanio: ["Grande"],
      riego: ["Moderado", "Requiere riego frecuente"],
      clima: ["Clima templado", "Resistente al calor"],
      mascotas: ["Tóxica para mascotas"],
    },
    {
      name: "Colisandra",
      nameSpanish: "Colisandra",
      scientificName: "",
      imageUrl: "",
      desc: "",
      tipo: ["Exterior"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Pequeña", "Mediana"],
      riego: ["Moderado"],
      clima: ["Resistente al calor"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Palma areca mini",
      nameSpanish: "Palma Areca Mini",
      scientificName: "",
      imageUrl: "",
      desc: "",
      tipo: ["Interior"],
      luzRequerida: ["Interior con luz brillante indirecta", "Sombra parcial"],
      tamanio: ["Pequeña", "Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },

    {
      name: "Monstera deliciosa",
      nameSpanish: "Monstera deliciosa",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755660394/monstera_delis_jiba8j.png",
      desc: "",
      tipo: ["Interior", "Exterior"],
      luzRequerida: ["Sombra parcial", "Interior con luz brillante indirecta"],
      tamanio: ["Grande"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Pata de elefante",
      nameSpanish: "Pata de elefante",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755660436/pata_elefante_u85bmh.png",
      desc: "",
      tipo: ["Exterior"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Grande"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Resistente al calor", "Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Palo de Brasil",
      nameSpanish: "Palo de Brasil",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755660478/palo_de_brasil_2_glj8uf.png",
      desc: "",
      tipo: ["Interior", "Exterior"],
      luzRequerida: ["Sombra parcial", "Interior con luz brillante indirecta"],
      tamanio: ["Mediana", "Grande"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Crasula",
      nameSpanish: "Crasula",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755660514/crasula_jfttlz.png",
      desc: "",
      tipo: ["Interior", "Exterior", "Suculentas"],
      luzRequerida: ["Sol directo", "Sombra parcial"],
      tamanio: ["Pequeña", "Mediana"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado", "Resistente al calor"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Crasula lanugilosa",
      nameSpanish: "Crasula lanugilosa",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755660552/crasula_lanugilosa_udseph.png",
      desc: "",
      tipo: ["Interior", "Exterior", "Suculentas"],
      luzRequerida: ["Sol directo", "Sombra parcial"],
      tamanio: ["Pequeña"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Acordeon",
      nameSpanish: "Acordeon",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755660584/acordeon_kzosha.png",
      desc: "",
      tipo: ["Interior", "Suculentas"],
      luzRequerida: ["Sombra parcial", "Interior con luz brillante indirecta"],
      tamanio: ["Pequeña"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Aeonium variegado",
      nameSpanish: "Aeonium variegado",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755660751/aeonium_variegado_ufaljz.png",
      desc: "",
      tipo: ["Exterior", "Suculentas"],
      luzRequerida: ["Sol directo", "Sombra parcial"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado", "Resistente al calor"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Planta diamante",
      nameSpanish: "Planta diamante",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755660802/diamante_yv3tof.png",
      desc: "",
      tipo: ["Interior", "Suculentas"],
      luzRequerida: ["Interior con luz brillante indirecta", "Sombra parcial"],
      tamanio: ["Pequeña"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Crazula pellucida",
      nameSpanish: "Crazula pellucida",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755660847/Crazula_pellucida_tdkkus.png",
      desc: "",
      tipo: ["Interior", "Suculentas"],
      luzRequerida: ["Sol directo", "Sombra parcial"],
      tamanio: ["Pequeña", "Mediana"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },

    {
      name: "Crassula capitella",
      nameSpanish: "Crassula capitella",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755660886/Crassula_capitella_zotphm.png",
      desc: "",
      tipo: ["Exterior", "Suculentas"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado", "Resistente al calor"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Crassula perforada",
      nameSpanish: "Crassula perforada",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755660926/crassula_perforada_zdhxun.png",
      desc: "",
      tipo: ["Interior", "Suculentas"],
      luzRequerida: ["Sombra parcial", "Interior con luz brillante indirecta"],
      tamanio: ["Pequeña"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Sempervivum ciliosum",
      nameSpanish: "Sempervivum ciliosum",
      scientificName: "",
      imageUrl: "",
      desc: "",
      tipo: ["Exterior", "Suculentas"],
      luzRequerida: ["Sol directo", "Sombra parcial"],
      tamanio: ["Pequeña", "Mediana"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Resistente al frío", "Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Graptopetalum amethystinum",
      nameSpanish: "Graptopetalum amethystinum",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755661049/Graptopetalum_amethystinum_2_gamrye.png",
      desc: "",
      tipo: ["Interior", "Suculentas"],
      luzRequerida: ["Sombra parcial", "Interior con luz brillante indirecta"],
      tamanio: ["Pequeña"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Rosa mármol",
      nameSpanish: "Rosa mármol",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755661099/Rosa_m%C3%A1rmol_v3hxvz.png",
      desc: "",
      tipo: ["Interior", "Suculentas"],
      luzRequerida: ["Sol directo", "Sombra parcial"],
      tamanio: ["Pequeña", "Mediana"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Echevverria pulidonis",
      nameSpanish: "Echevverria pulidonis",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755661135/Echevverria_pulidonis_rwso5y.png",
      desc: "",
      tipo: ["Interior", "Suculentas"],
      luzRequerida: ["Sombra parcial", "Interior con luz brillante indirecta"],
      tamanio: ["Pequeña"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Echeverria secunda",
      nameSpanish: "Echeverria secunda",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755661169/Echeverria_secunda_mpitua.png",
      desc: "",
      tipo: ["Interior", "Suculentas"],
      luzRequerida: ["Sombra parcial", "Interior con luz brillante indirecta"],
      tamanio: ["Pequeña"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Echeverria secunda glauca",
      nameSpanish: "Echeverria secunda glauca",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755661203/Echeverria_secunda_glauca_zr64sx.png",
      desc: "",
      tipo: ["Interior", "Suculentas"],
      luzRequerida: ["Sombra parcial", "Interior con luz brillante indirecta"],
      tamanio: ["Pequeña"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },

    {
      name: "Echeverria prolifica",
      nameSpanish: "Echeverria prolifica",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755661237/echeveria_prolifica_qcejp3.png",
      desc: "",
      tipo: ["Interior", "Suculentas"],
      luzRequerida: ["Sombra parcial", "Interior con luz brillante indirecta"],
      tamanio: ["Pequeña"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Sedum",
      nameSpanish: "Sedum",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755661352/sedum%C3%A7_itnq0u.png",
      desc: "",
      tipo: ["Exterior", "Suculentas"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Pequeña", "Mediana"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado", "Resistente al calor"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Senecio rubí",
      nameSpanish: "Senecio rubí",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755661385/Senecio_rub%C3%AD_kowc0c.png",
      desc: "",
      tipo: ["Exterior", "Suculentas"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Pequeña"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Clima templado", "Resistente al calor"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Echeverria aelegans rose",
      nameSpanish: "Echeverria aelegans rose",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755661414/Echeverria_aelegans_rose_vjsjkn.png",
      desc: "",
      tipo: ["Interior", "Suculentas"],
      luzRequerida: ["Sombra parcial", "Interior con luz brillante indirecta"],
      tamanio: ["Pequeña"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Echeverria",
      nameSpanish: "Echeverria",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755661454/Echeverria_dyx8tf.png",
      desc: "",
      tipo: ["Interior", "Suculentas"],
      luzRequerida: ["Sombra parcial", "Interior con luz brillante indirecta"],
      tamanio: ["Pequeña"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Agabe azul",
      nameSpanish: "Agave azul",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755661493/Agabe_azul_2_kddoob.png",
      desc: "",
      tipo: ["Exterior", "Arbustos"],
      luzRequerida: ["Sol directo"],
      tamanio: ["Mediana", "Grande"],
      riego: ["Bajo mantenimiento (poca agua)"],
      clima: ["Resistente al calor", "Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Rosario",
      nameSpanish: "Rosario",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755661527/Rosario_letpog.png",
      desc: "",
      tipo: ["Interior", "Suculentas"],
      luzRequerida: ["Sombra parcial", "Interior con luz brillante indirecta"],
      tamanio: ["Pequeña"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Orega de shrek",
      nameSpanish: "Oreja de Shrek",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755661556/Orega_de_shrek_yvyobc.png",
      desc: "",
      tipo: ["Interior", "Suculentas"],
      luzRequerida: ["Sombra parcial", "Interior con poca luz"],
      tamanio: ["Pequeña", "Mediana"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Garita de oso",
      nameSpanish: "Garita de oso",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755661599/Garita_de_oso_xrecnc.png",
      desc: "",
      tipo: ["Interior", "Suculentas"],
      luzRequerida: ["Sombra parcial"],
      tamanio: ["Pequeña"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
    {
      name: "Ciolita de borrego",
      nameSpanish: "Ciolita de borrego",
      scientificName: "",
      imageUrl:
        "https://res.cloudinary.com/dso8cvvoe/image/upload/v1755661630/Ciolita_de_borrego_sc9zxk.png",
      desc: "",
      tipo: ["Interior", "Suculentas"],
      luzRequerida: ["Sombra parcial", "Interior con poca luz"],
      tamanio: ["Pequeña"],
      riego: ["Moderado"],
      clima: ["Clima templado"],
      mascotas: ["Pet friendly"],
    },
  ];
  const { filtrosSeleccionados } = useFilterStore();
  const [plants, setPlants] = useState(allPlants);

  const filteredPlants = useMemo(() => {
    const filters = filtrosSeleccionados;

    return allPlants.filter((plant) => {
      const matchTipo =
        !filters.Tipo?.length ||
        filters.Tipo.some((tipo) => plant.tipo.includes(tipo));
      const matchLuz =
        !filters.Luz?.length ||
        filters.Luz.some((luz) => plant.luzRequerida.includes(luz));
      const matchTamaño =
        !filters.Tamaño?.length ||
        filters.Tamaño.some((tam) => plant.tamanio.includes(tam));
      const matchRiego =
        !filters.Riego?.length ||
        filters.Riego.some((riego) => plant.riego.includes(riego));
      const matchClima =
        !filters.Clima?.length ||
        filters.Clima.some((clima) => plant.clima.includes(clima));
      const matchMascotas =
        filters.Mascotas == null || plant.mascotas === filters.Mascotas[0];

      return (
        matchTipo &&
        matchLuz &&
        matchTamaño &&
        matchRiego &&
        matchClima &&
        matchMascotas
      );
    });
  }, [filtrosSeleccionados]);

  function getRandomObjects(arr, count = 9) {
    // Copiamos el arreglo para no modificar el original
    const shuffled = [...arr].sort(() => Math.random() - 0.5);
    // Retornamos los primeros 'count' elementos
    return shuffled.slice(0, count);
  }

  return { plants, filteredPlants, randomPlants };
};
